using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace Xml2Doc.Core.OutputLifecycle
{
    /// <summary>
    /// Applies a validated output lifecycle plan after output generation succeeds.
    /// </summary>
    public static class OutputLifecycleExecutor
    {
        /// <summary>
        /// Plans and optionally applies stale-output cleanup for a successful generation.
        /// </summary>
        /// <param name="location">The invocation-scoped manifest location.</param>
        /// <param name="generatedFiles">
        /// The complete output-root-relative file set generated by the invocation.
        /// </param>
        /// <param name="dryRun">
        /// <see langword="true"/> to return the plan without changing files or ownership.
        /// </param>
        /// <returns>The deterministic lifecycle plan.</returns>
        public static OutputLifecyclePlan ExecuteAfterSuccessfulGeneration(
            OutputManifestLocation location,
            IReadOnlyList<string> generatedFiles,
            bool dryRun = false)
        {
            if (location is null)
            {
                throw new ArgumentNullException(nameof(location));
            }

            if (generatedFiles is null)
            {
                throw new ArgumentNullException(nameof(generatedFiles));
            }

            var previousManifest = OutputManifestStore.Load(location);
            var plan = OutputManifestPlanner.CreatePlan(
                location.OutputRoot,
                generatedFiles,
                previousManifest);

            if (dryRun)
            {
                return plan;
            }

            ValidateGeneratedFilesExist(
                location.OutputRoot,
                plan.FilesToWrite);
            ApplyPlan(location, plan);
            return plan;
        }

        private static void ValidateGeneratedFilesExist(
            string outputRoot,
            IReadOnlyList<string> filesToWrite)
        {
            foreach (var relativePath in filesToWrite)
            {
                var fullPath =
                    outputRoot + Path.DirectorySeparatorChar +
                    relativePath;

                if (!File.Exists(fullPath))
                {
                    throw new InvalidOperationException(
                        $"Generated output '{relativePath}' does not exist.");
                }
            }
        }

        private static void ApplyPlan(
            OutputManifestLocation location,
            OutputLifecyclePlan plan)
        {
            var transactionDirectory = CreateTransactionDirectory(location);
            var stagedFiles = new List<StagedFile>();
            var manifestCommitted = false;

            try
            {
                StageStaleFiles(
                    location,
                    plan.FilesToDelete,
                    transactionDirectory,
                    stagedFiles);

                OutputManifestStore.Save(
                    location,
                    plan.FilesToWrite);
                manifestCommitted = true;
            }
            catch
            {
                if (!manifestCommitted)
                {
                    RestoreStagedFiles(stagedFiles);
                }

                throw;
            }
            finally
            {
                if (manifestCommitted &&
                    Directory.Exists(transactionDirectory))
                {
                    Directory.Delete(
                        transactionDirectory,
                        recursive: true);
                }
                else
                {
                    DeleteDirectoryIfEmpty(transactionDirectory);
                }
            }
        }

        private static string CreateTransactionDirectory(
            OutputManifestLocation location)
        {
            var manifestDirectory = Path.GetDirectoryName(
                location.ManifestPath);
            var metadataDirectory = manifestDirectory is null
                ? null
                : Path.GetDirectoryName(manifestDirectory);

            if (string.IsNullOrEmpty(metadataDirectory))
            {
                throw new InvalidOperationException(
                    "The manifest path does not contain a metadata directory.");
            }

            var transactionDirectory =
                metadataDirectory + Path.DirectorySeparatorChar +
                "transactions" + Path.DirectorySeparatorChar +
                location.IdentityHash + "-" +
                Guid.NewGuid().ToString("N");

            Directory.CreateDirectory(transactionDirectory);
            return transactionDirectory;
        }

        private static void StageStaleFiles(
            OutputManifestLocation location,
            IReadOnlyList<string> filesToDelete,
            string transactionDirectory,
            ICollection<StagedFile> stagedFiles)
        {
            for (var index = 0; index < filesToDelete.Count; index++)
            {
                var relativePath = filesToDelete[index];
                var sourcePath =
                    location.OutputRoot + Path.DirectorySeparatorChar +
                    relativePath;

                if (!File.Exists(sourcePath))
                {
                    continue;
                }

                EnsureNoReparsePointInRelativePath(
                    location.OutputRoot,
                    relativePath);

                var stagedPath =
                    transactionDirectory + Path.DirectorySeparatorChar +
                    index.ToString("D8") + ".staged";

                File.Move(sourcePath, stagedPath);
                stagedFiles.Add(new StagedFile(sourcePath, stagedPath));
            }
        }

        private static void EnsureNoReparsePointInRelativePath(
            string outputRoot,
            string relativePath)
        {
            var separator = Path.DirectorySeparatorChar;
            var alternateSeparator = Path.AltDirectorySeparatorChar;
            var segments = relativePath.Split(
                new[] { separator, alternateSeparator },
                StringSplitOptions.RemoveEmptyEntries);
            var pathBuilder = new StringBuilder(outputRoot);

            for (var index = 0; index < segments.Length - 1; index++)
            {
                pathBuilder
                    .Append(separator)
                    .Append(segments[index]);
                var currentPath = pathBuilder.ToString();

                if (Directory.Exists(currentPath) &&
                    (File.GetAttributes(currentPath) &
                     FileAttributes.ReparsePoint) != 0)
                {
                    throw new IOException(
                        "Stale output cleanup cannot traverse a filesystem reparse point.");
                }
            }
        }

        private static void RestoreStagedFiles(
            IReadOnlyList<StagedFile> stagedFiles)
        {
            for (var index = stagedFiles.Count - 1; index >= 0; index--)
            {
                var stagedFile = stagedFiles[index];
                var destinationDirectory = Path.GetDirectoryName(
                    stagedFile.OriginalPath);

                if (!string.IsNullOrEmpty(destinationDirectory))
                {
                    Directory.CreateDirectory(destinationDirectory);
                }

                if (File.Exists(stagedFile.StagedPath))
                {
                    File.Move(
                        stagedFile.StagedPath,
                        stagedFile.OriginalPath);
                }
            }
        }

        private static void DeleteDirectoryIfEmpty(string directory)
        {
            if (Directory.Exists(directory) &&
                Directory.GetFileSystemEntries(directory).Length == 0)
            {
                Directory.Delete(directory);
            }
        }

        private sealed class StagedFile
        {
            public StagedFile(
                string originalPath,
                string stagedPath)
            {
                OriginalPath = originalPath;
                StagedPath = stagedPath;
            }

            public string OriginalPath { get; }

            public string StagedPath { get; }
        }
    }
}
