[CmdletBinding()]
param(
  [ValidateSet("Debug", "Release")]
  [string] $Configuration = "Release",

  [switch] $KeepArtifacts
)

$ErrorActionPreference = "Stop"

function RepoRoot
{
  (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
}

function Write-Step([string] $Message)
{
  Write-Host ""
  Write-Host "==> $Message"
}

function Assert-True($Condition, [string] $Message)
{
  if (-not $Condition) { throw $Message }
}

function Run-Capture
{
  param(
    [Parameter(Mandatory = $true)][string] $FileName,
    [Parameter(Mandatory = $true)][string] $Arguments,
    [Parameter(Mandatory = $true)][string] $WorkingDirectory
  )

  $psi = [System.Diagnostics.ProcessStartInfo]::new()
  $psi.FileName = $FileName
  $psi.Arguments = $Arguments
  $psi.WorkingDirectory = $WorkingDirectory
  $psi.UseShellExecute = $false
  $psi.RedirectStandardOutput = $true
  $psi.RedirectStandardError = $true
  $psi.CreateNoWindow = $true

  $process = [System.Diagnostics.Process]::new()
  $process.StartInfo = $psi
  [void]$process.Start()
  $stdout = $process.StandardOutput.ReadToEnd()
  $stderr = $process.StandardError.ReadToEnd()
  $process.WaitForExit()

  [pscustomobject]@{
    ExitCode = $process.ExitCode
    StdOut = $stdout
    StdErr = $stderr
  }
}

function Run-OrThrow
{
  param(
    [Parameter(Mandatory = $true)][string] $File,
    [Parameter(Mandatory = $true)][string] $Args,
    [Parameter(Mandatory = $true)][string] $Cwd,
    [string] $ErrorPrefix = "Command failed"
  )

  Write-Host "    CMD: $File $Args"
  $result = Run-Capture -FileName $File -Arguments $Args -WorkingDirectory $Cwd
  if ($result.ExitCode -ne 0)
  {
    throw "$ErrorPrefix`n`nCMD: $File $Args`n`nSTDOUT:`n$($result.StdOut)`n`nSTDERR:`n$($result.StdErr)"
  }

  return $result
}

function Write-TextFile([string] $Path, [string] $Content)
{
  $directory = Split-Path $Path -Parent
  if ($directory -and -not (Test-Path $directory))
  {
    New-Item -ItemType Directory -Force -Path $directory | Out-Null
  }

  [System.IO.File]::WriteAllText($Path, $Content)
}

function Escape-Xml([string] $Value)
{
  [System.Security.SecurityElement]::Escape($Value)
}

function Get-Snapshot([string] $Root)
{
  $rootPath = (Resolve-Path $Root).Path.TrimEnd('\', '/')
  $snapshot = [ordered]@{}

  Get-ChildItem -Path $rootPath -Recurse -File |
    Sort-Object FullName |
    ForEach-Object {
      $relative = $_.FullName.Substring($rootPath.Length).TrimStart('\', '/') -replace '\\', '/'
      $snapshot[$relative] = (Get-FileHash -Algorithm SHA256 -LiteralPath $_.FullName).Hash
    }

  $snapshot
}

function Assert-SnapshotsEqual($Expected, $Actual)
{
  $expectedNames = @($Expected.Keys)
  $actualNames = @($Actual.Keys)
  Assert-True (($expectedNames -join "`n") -ceq ($actualNames -join "`n")) (
    "Generated file sets differ.`nExpected:`n$($expectedNames -join "`n")`nActual:`n$($actualNames -join "`n")")

  foreach ($name in $expectedNames)
  {
    Assert-True ($Expected[$name] -eq $Actual[$name]) "Generated bytes differ for '$name'."
  }
}

$repo = RepoRoot
$taskProject = Join-Path $repo "Xml2Doc/src/Xml2Doc.MSBuild/Xml2Doc.MSBuild.csproj"
$propsPath = Join-Path $repo "Xml2Doc/src/Xml2Doc.MSBuild/build/Xml2Doc.MSBuild.props"
$targetsPath = Join-Path $repo "Xml2Doc/src/Xml2Doc.MSBuild/build/Xml2Doc.MSBuild.targets"
$aggregateTargetsPath = Join-Path $repo "Xml2Doc/src/Xml2Doc.MSBuild/build/Xml2Doc.MSBuild.Aggregation.targets"

foreach ($path in @($taskProject, $propsPath, $targetsPath, $aggregateTargetsPath))
{
  Assert-True (Test-Path $path) "Required integration input not found: $path"
}

$runId = [guid]::NewGuid().ToString("n")
$runRoot = Join-Path $repo "artifacts/msbuild-aggregation/$Configuration/$runId"
$alphaDir = Join-Path $runRoot "Alpha"
$zuluDir = Join-Path $runRoot "Zulu"
$ownerDir = Join-Path $runRoot "Owner"
$parallelDocs = Join-Path $runRoot "docs-parallel"
$serialDocs = Join-Path $runRoot "docs-serial"
$parallelReport = Join-Path $runRoot "parallel-report.json"
$serialReport = Join-Path $runRoot "serial-report.json"

New-Item -ItemType Directory -Force -Path $runRoot | Out-Null

Write-Step "Building Xml2Doc.MSBuild task assembly"
Run-OrThrow -File "dotnet" -Args "build `"$taskProject`" --configuration $Configuration --disable-build-servers" -Cwd $repo -ErrorPrefix "Task assembly build failed."

$libraryProject = @'
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>
</Project>
'@

Write-TextFile (Join-Path $alphaDir "Alpha.csproj") $libraryProject
Write-TextFile (Join-Path $alphaDir "Widget.cs") @"
namespace Alpha.Api;

/// <summary>Alpha widget.</summary>
public sealed class Widget
{
    /// <summary>Runs Alpha work.</summary>
    public void Run() { }
}
"@

Write-TextFile (Join-Path $zuluDir "Zulu.csproj") $libraryProject
Write-TextFile (Join-Path $zuluDir "Widget.cs") @"
namespace Zulu.Api;

/// <summary>Zulu widget.</summary>
public sealed class Widget
{
    /// <summary>Runs Zulu work.</summary>
    public void Run() { }
}
"@

$propsImport = Escape-Xml $propsPath
$targetsImport = Escape-Xml $targetsPath
$aggregateTargetsImport = Escape-Xml $aggregateTargetsPath
$ownerProject = @"
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <Xml2Doc_Enabled>false</Xml2Doc_Enabled>
    <Xml2Doc_AggregateEnabled>true</Xml2Doc_AggregateEnabled>
    <Xml2Doc_AggregateValidateIndexOwnership>true</Xml2Doc_AggregateValidateIndexOwnership>
    <Xml2Doc_FileNameMode>clean</Xml2Doc_FileNameMode>
    <Xml2Doc_GenerateIndex>true</Xml2Doc_GenerateIndex>
    <Xml2Doc_ReportIncludeTimestamp>false</Xml2Doc_ReportIncludeTimestamp>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Alpha/Alpha.csproj" />
    <ProjectReference Include="../Zulu/Zulu.csproj" />
  </ItemGroup>
  <Import Project="$propsImport" />
  <Import Project="$targetsImport" />
  <Import Project="$aggregateTargetsImport" />
</Project>
"@
$ownerProjectPath = Join-Path $ownerDir "Owner.csproj"
Write-TextFile $ownerProjectPath $ownerProject

Write-Step "Restoring repository aggregation projects"
Run-OrThrow -File "dotnet" -Args "restore `"$ownerProjectPath`" --disable-build-servers" -Cwd $repo -ErrorPrefix "Repository aggregation restore failed."

function Invoke-OwnerBuild
{
  param(
    [Parameter(Mandatory = $true)][string] $OutputDirectory,
    [Parameter(Mandatory = $true)][string] $ReportPath,
    [Parameter(Mandatory = $true)][string] $MaxCpuArgument,
    [Parameter(Mandatory = $true)][string] $Label
  )

  Write-Step $Label
  $args =
    "msbuild `"$ownerProjectPath`" /t:Rebuild /p:Configuration=$Configuration " +
    "/p:Xml2Doc_OutputDir=`"$OutputDirectory`" " +
    "/p:Xml2Doc_AggregateReportPath=`"$ReportPath`" " +
    "$MaxCpuArgument /nr:false /nodeReuse:false /v:minimal"
  Run-OrThrow -File "dotnet" -Args $args -Cwd $repo -ErrorPrefix "$Label failed."
}

Invoke-OwnerBuild -OutputDirectory $parallelDocs -ReportPath $parallelReport -MaxCpuArgument "/m" -Label "Parallel repository build"
Invoke-OwnerBuild -OutputDirectory $serialDocs -ReportPath $serialReport -MaxCpuArgument "/m:1" -Label "Serial repository build"

Write-Step "Comparing parallel and serial aggregate output"
Assert-True (Test-Path (Join-Path $parallelDocs "index.md")) "Parallel build did not generate index.md."
Assert-True (Test-Path (Join-Path $serialDocs "index.md")) "Serial build did not generate index.md."

$parallelSnapshot = Get-Snapshot $parallelDocs
$serialSnapshot = Get-Snapshot $serialDocs
Assert-SnapshotsEqual $parallelSnapshot $serialSnapshot

$index = Get-Content (Join-Path $parallelDocs "index.md") -Raw
$alphaIndex = $index.IndexOf("Alpha.Api.Widget", [StringComparison]::Ordinal)
$zuluIndex = $index.IndexOf("Zulu.Api.Widget", [StringComparison]::Ordinal)
Assert-True ($alphaIndex -ge 0) "Aggregate index does not contain Alpha.Api.Widget."
Assert-True ($zuluIndex -gt $alphaIndex) "Aggregate index is not in stable ordinal project/type order."

$reportModel = Get-Content $parallelReport -Raw | ConvertFrom-Json
Assert-True ($reportModel.xmlInputs.Count -eq 2) "Expected exactly two aggregate XML inputs in the report."
$reportedInputs = @($reportModel.xmlInputs)
$sortedInputs = @($reportedInputs | Sort-Object -CaseSensitive)
Assert-True (($reportedInputs -join "`n") -ceq ($sortedInputs -join "`n")) "Aggregate report XML inputs are not canonically ordered."

Write-Step "MSBuild repository aggregation integration completed successfully"
Write-Host "MSBuild aggregation integration OK. Artifacts: $runRoot"

if (-not $KeepArtifacts)
{
  Remove-Item -Recurse -Force $runRoot
}
