name: Merge Test Workflow
permissions:
  contents: read

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - "docs/**"
      - "README.md"
      - "CHANGELOG.md"
      - "RELEASE.md"
      - "Xml2Doc.md"

jobs:
  run_tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET (global.json)
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: ./global.json

      - name: Clean
        run: dotnet clean ${{ github.workspace }}/${{ vars.PROJECT_NAME }}/${{ vars.PROJECT_NAME }}.sln --configuration Release --disable-build-servers

      - name: Restore dependencies
        run: dotnet restore ${{ github.workspace }}/${{ vars.PROJECT_NAME }}/${{ vars.PROJECT_NAME }}.sln --disable-build-servers

      - name: Build
        run: dotnet build ${{ github.workspace }}/${{ vars.PROJECT_NAME }}/${{ vars.PROJECT_NAME }}.sln --configuration Release --no-restore --disable-build-servers

      - name: Test (exclude integration)
        run: dotnet test ${{ github.workspace }}/${{ vars.PROJECT_NAME }}/${{ vars.PROJECT_NAME }}.sln --configuration Release --no-build --logger "trx;LogFileName=test_results.trx" --filter "Category!=Integration"

      - name: Publish Test Results
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: Test Results
          path: '**/TestResults/*.trx'